### ISSUE TITLE
Don't honor workspace flag if app is running

### ISSUE THREAD

**Issue by petobens** [open-dynaMIX/raiseorlaunch#15]
Hi! First all thanks for writing raiseorlaunch, it's super useful.

I have one question/request. I have the following binding in my config file:
```
set $ws1 "1"
bindsym $mod+Control+i $nexec raiseorlaunch -c Chromium -w $ws1
```
that will open Chromimum on in workspace 1. However if I now move the Chromium window to workspace 2 and then run the binding again then raiseorlaunch opens a new Chromium window/instance in workspace 1. I would like to know if it's possible to add a flag or something that will switch focus to the app if it's already running even if the `-w` was specified: i.e focus Chromium window in workspace 1 instead of opening a new one in workspace 2.

Thanks in advance!

**Comment by open-dynaMIX** [comment]
Hi @petobens 

I can think of a limited solution to make this work without changes in raiseorlaunch:

```
set $ws1 "1
bindsym $mod+Control+i exec raiseorlaunch -c Chromium -e "--no-startup-id \\\"i3-msg workspace $ws1 && chromium\\\""
```

It's rather ugly, but works. The limitation is, that if you have set `workspace_auto_back_and_forth yes` and already are on workspace 1, it will open chromium on the previously focused workspace.

Please let me know, if this workaround is sufficient for you.

**Comment by petobens** [comment]
It works! So I don't mind if it's ugly  :). Can you explain a bit exactly why/how this works? (and close this issue after that).
Thank you!

**Comment by open-dynaMIX** [comment]
Great!

We call raiseorlaunch without the `-w`argument, so in subsequent calls, it doesn't care about the workspace the application is on.

The `-e` argument (which is passed to i3s `exec`)...
 - ...tells i3 to ignore startup-notifications (`--no-startup-id`). Without that the window would be created on the workspace that was focussed when triggering the bindsym (given that the application provides desktop-notifications)
 - ...switches to the desired workspace with `i3-msg`
 - ...then runs chromium

Generally I'd recommend to always use `--no-startup-id` when calling raiseorlaunch, because raiseorlaunch itself doesn't create any window and hence doesn't provide startup-notifications.

Additionally I was able to de-uglify the bindsym a bit:
```
bindsym $mod+Control+i exec --no-startup-id raiseorlaunch -c Chromium -e "--no-startup-id i3-msg workspace $ws1 && chromium"
```

**Comment by petobens** [comment]
Excellent. Thanks once again.

**Comment by petobens** [comment]
Hi, I have one more question which I'm asking here because i don't know if it's related to this specific binding or not; i can open a new issue if you want me to).

Following your suggestions I have now the following in my config file:
```
set $nexec exec --no-startup-id
bindsym $mod+Control+p $nexec raiseorlaunch -c Zathura -e \
    "--no-startup-id i3-msg workspace "2" && zathura"
```
Now imagine that I have 3 Zathura windows opened: 2 in workspace "2" and 1 in workpsace "1". If run the binding then `raiseorlaunch` will switch focus between the 2 windows in workspace 2 and ignore the one in workspace 1. Is it possible to also include the window in workspace 1 when cycling?

Thanks and sorry for all the questions :)

**Comment by open-dynaMIX** [comment]
Hi!
Cycling through windows is not implemented atm. My own workflow heavily depends on `workspace_auto_back_and_forth`, so I don't want cycling myself.

Right now, raiseorlaunch just focuses the first window it finds that match the provided properties.

Please open a new issue, requesting this feature and I will see, if I can provide a flag for this.

**Comment by petobens** [comment]
Done! Thanks :)

**Comment by open-dynaMIX** [comment]
I'm reopening this issue because my suggestion here does not play well with the fix for #16. So I guess the way to go is indeed to have an additional flag for setting the initial workspace.

**Comment by open-dynaMIX** [comment]
A fix for this can be found in the develop branch.

**Comment by petobens** [comment]
Been using this now for a couple of  days without problems :). Thanks!
