### ISSUE TITLE
Add flag to disable existing fullscreen

### ISSUE THREAD

**Issue by petobens** [open-dynaMIX/raiseorlaunch#27]
Hi! I was wondering if you could add a flag to disable an existing fullscreen in the workspace where the application is going to be launched (if there is any).
Thanks!

**Comment by open-dynaMIX** [comment]
Hey! I'm sorry, I'm very busy right now.

After a first look at it, ths seems fairly easy to implement.

I will do it, as soon as I find the  time. But please don't expect it this year.

**Comment by petobens** [comment]
Great! Thank you :) There is no rush.

**Comment by petobens** [comment]
Hi @open-dynaMIX thanks for the change! This  works great when specifying a workspace:
```
bindsym $mod+Control+g $nexec raiseorlaunch -c Peek -f -W $ws5
```
I was wondering if you could extend it to avoid having to specify a workspace. Following the example above I want to run  from within some workspace:
```
bindsym $mod+Control+g $nexec raiseorlaunch -c Peek -f
```
and if there is a full screen in that workspace where the Peek app is going to launch/focus then disable it.

Thanks once again!

**Comment by open-dynaMIX** [comment]
@petobens Thank you very much for pointing this out. That's actually a bug and I'm working on a fix right now. It's tracked in #30.
