### ISSUE TITLE
cannot run commands that contain a space

### ISSUE THREAD

**Issue by dansteen** [open-dynaMIX/raiseorlaunch#5]
Hi!

Thanks for your work on this!  It really increases my productivity with i3.

I did run into one issue, that it is impossible to run a command with a space in the name.  I tried:

- /opt/Pulse SMS/pulse-sms
- /opt/Pulse\ SMS/pulse-sms
- '/opt/Pulse SMS/pulse-sms'
- "/opt/Pulse SMS/pulse-sms"

Then I really went out on a limb and tried
- /opt/Pulse\\\\ SMS/pulse-sms
- "'/opt/Pulse SMS/pulse-sms'"  (single quotes surrounded by double quotes)
- '"/opt/Pulse SMS/pulse-sms"' (double quotes surrounded by single quotes)
- '\"/opt/Pulse SMS/pulse-sms\"' (escaped double quotes surrounded by single quotes)
- "\'/opt/Pulse SMS/pulse-sms\'" (escaped single quotes surrounded by double quotes)

Now, I agree that spaces in names are really horrible things :-) but sometimes I just need to work with them.  

Thanks so much!

**Comment by dansteen** [comment]
On further analysis, I see that its taking the second part of the name and passing it in as a paramater to the first.

**Comment by open-dynaMIX** [comment]
Nice to hear it's useful for you :)

Jup, that's a bug. I guess the check if it's an executable was a bit over-eager and needs to be removed if `-e` is provided.

It's fixed in the dev branch now, if you want to check. I will push a new release tomorrow.

Thanks for reporting!

**Comment by open-dynaMIX** [comment]
The fix is in master now. Also there is a new release (0.2.3) on Github, PyPI and the AUR.
