### ISSUE TITLE
Feature request: hide window if active

### ISSUE THREAD

**Issue by QiangF** [open-dynaMIX/raiseorlaunch#56]
Just like i3run, but I can't get it work for multiple monitors.

**Comment by open-dynaMIX** [comment]
Hey @QiangF 

Could you please be more specific. What's the actual behaviour? What's the behaviour you want?

If you want to move it to the scratchpad, you can use `-r`/`--scratch`.

**Comment by QiangF** [comment]
Currently it looks like raiseorlaunch just do what its name says, if the focus app doesn't match, raise or launch it. What I want is if the focused app did match the criterion, hide it by moving to a designated workspace or the scratchpad, optionally cycle through all the matched instances.
This way you have more functionality to one single keybinding.

**Comment by open-dynaMIX** [comment]
What you describe is pretty much what raiseorlaunch does (except the hiding to a designated workspace). I suggest you read through the examples in the README.

raiseorlaunch only does what you tell it to. If you want to use the scratchpad, you need to use `--scratch`. If you want to cycle through matching windows, you need to use `--cycle`. Also i3s `workspace_auto_back_and_forth` is worth mentioning (potentially clashes with `--cycle`).

**Comment by QiangF** [comment]
Thank you! I can't get the script to work for my two monitor setup. I am current using this

    #!/bin/bash

    # the options and its arguments is identical to what we are passing
    # to i3get later. So we store them in a array: acri for convenience.

    while getopts :c:i:t: option
    do
    case "${option}" in
        i) acri=("-i" "${OPTARG}") ;;
        c) acri=("-c" "${OPTARG}") ;;
        t) acri=("-t" "${OPTARG}") ;;
    esac
    done

    # the -e option is handled in a special way, since it might contain
    # more than one word. This is also the reason we want it as the last option.
    # with these line the whole command after -e is stored in command.
    shift $((--OPTIND))
    command=${@}

    # lets get the con_id of the currently active window and the current workspace.
    # we store the results in an array. active window is current[0] and active 
    # workspace is current[1]
    current=($(i3get -r nw))
    # active_ws_name=$(i3-msg -t get_workspaces | jq -r 'map(select(.focused))[0].name')

    # check what target window is up to:
    target=($(i3get ${acri[@]} -r nwf))

    # if window doesn't exist, launch the command.
    # use i3get with -y (synch) option, to catch the con_id of the new window.
    if [[ -z ${target[0]} ]]; then
    ${command} > /dev/null 2>&1 & 
    target=($(i3get ${acri[@]} -y -r nw))
    fi

    # not same workspace
    if [[ ${current[1]} != ${target[1]} ]]; then
        i3-msg [con_id=${target[0]}] \
            move to workspace current focus > /dev/null 2>&1
    else
        # under focus
        if [[ ${current[0]} = ${target[0]} ]]; then
            i3-msg [con_id=${target[0]}] \
                move to workspace 8 > /dev/null 2>&1
        else
            i3-msg [con_id=${target[0]}] focus > /dev/null 2>&1
        fi
    fi
