### ISSUE TITLE
-w results in the window being opened on the current workspace rather than the named one

### ISSUE THREAD

**Issue by dansteen** [open-dynaMIX/raiseorlaunch#8]
Hi!

It looks like -w is not moving the window the the named workspace.   Instead it opens the window on the current workspace and then switches the user to the named workspace (but not the window)

Thanks!
(sorry for all the tickets)

**Comment by open-dynaMIX** [comment]
Hey!

Could you please provide the output of the command with the `-d`-flag?

Generally it moves to the workspace and then runs the command. However, I observed this problem with chromium. Based on the output, it did everything as desired, but then chromium seemed to have just opened on a random workspace. So far I wasn't able to isolate the problem.

Moving the window after the command is run could be quite difficult, as we don't know at what point the window is ready.

**Comment by dansteen** [comment]
Here is the output with the -d flag:

```
DEBUG:raiseorlaunch.__main__:Provided arguments: Namespace(command='firefox -P apps --new-window inbox.google.com', debug=True, ignore_case=True, scratch=False, wm_class='firefox', wm_instance='', wm_title='', workspace='mirage')
DEBUG:raiseorlaunch.raiseorlaunch:Getting i3 tree for workspace: mirage.
WARNING:raiseorlaunch.raiseorlaunch:No active windows found.
DEBUG:raiseorlaunch.raiseorlaunch:Currently focused workspace: 1:term
DEBUG:raiseorlaunch.raiseorlaunch:Application is not running.
DEBUG:raiseorlaunch.raiseorlaunch:Switching to workspace: mirage
DEBUG:raiseorlaunch.raiseorlaunch:Executing command: firefox -P apps --new-window inbox.google.com
```

Additionally, I find that I only have this issue if i trigger the command from a `bindsym` in i3.  But if I run the command on the command line eveything works just fine.  For reference, here is the output when it is run from the command line:
```
[~]$ raiseorlaunch -e "firefox -P apps --new-window inbox.google.com" -i -c "firefox" -w mirage -d                         
DEBUG:raiseorlaunch.__main__:Provided arguments: Namespace(command='firefox -P apps --new-window inbox.google.com', debug=True, ignore_case=True, scratch=False, wm_class='firefox', wm_instance='', wm_title='', workspace='mirage')
DEBUG:raiseorlaunch.raiseorlaunch:Getting i3 tree for workspace: mirage.
WARNING:raiseorlaunch.raiseorlaunch:No active windows found.
DEBUG:raiseorlaunch.raiseorlaunch:Currently focused workspace: 1:term
DEBUG:raiseorlaunch.raiseorlaunch:Application is not running.
DEBUG:raiseorlaunch.raiseorlaunch:Switching to workspace: mirage
DEBUG:raiseorlaunch.raiseorlaunch:Executing command: firefox -P apps --new-window inbox.google.com
```

**Comment by dansteen** [comment]
It doesn't appear to be a timing thing.  The following has the same result:
```
bindsym $mod+Shift+i exec "raiseorlaunch -e \\"sleep 5 ; firefox -P apps --new-window inbox.google.com\\" -i -c \\"firefox\\" -w mirage -d &> /tmp/log"
```

That bit of awful cases a 5 second sleep before launching the application but *after* switching windows, and the window still opens on the original workspace not the new one.

If anything I would say it seems like its somehow not picking up the correct workspace.  The following results in the correct behavior:
```
bindsym $mod+Shift+i workspace mirage; exec raiseorlaunch -e "firefox -P apps --new-window inbox.google.com" -i -c "firefox" -w mirage
```

**Comment by open-dynaMIX** [comment]
It seems to me you're missing the `--no-startup-id`-flag. Could you please try with following bindsym:

```
bindsym [your keys] exec --no-startup-id "raiseorlaunch [your options]"
```

**Comment by dansteen** [comment]
yup! that solved it.  I knew about that flag, but didn't think about it in this context.   Thanks!
